# overall_scorecard_app.py (for example)

import json
import pandas as pd
import streamlit as st
from PyPDF2 import PdfReader  # we'll add this to requirements.txt

JSON_PREFIX = "AB_SCORECARD_JSON:"

st.set_page_config(page_title="Overall Monthly Scorecard Summary", layout="wide")

st.title("Overall Monthly Scorecard Summary")

st.write("Upload the department scorecard PDFs generated by the Monthly Scorecard app.")


# 1. Upload PDFs
uploaded_files = st.file_uploader(
    "Upload scorecard PDFs",
    type=["pdf"],
    accept_multiple_files=True,
)

if not uploaded_files:
    st.stop()


# 2. Extract JSON from each PDF
all_rows = []

for f in uploaded_files:
    reader = PdfReader(f)
    info = reader.metadata or {}
    subject = getattr(info, "subject", None) or info.get("/Subject") or ""

    if JSON_PREFIX not in subject:
        st.warning(f"No embedded data found in {f.name}, skipping.")
        continue

    _, json_str = subject.split(JSON_PREFIX, 1)
    payload = json.loads(json_str)

    # Turn this payload into rows (one per question)
    meta = payload.get("meta", {})
    questions = payload.get("questions", [])
    overall_score = payload.get("scores", {}).get("overall_score")
    pillar_scores = payload.get("scores", {}).get("pillar_scores", {})

    for q in questions:
        all_rows.append({
            "source_file": f.name,
            "month": meta.get("month"),
            "month_label": meta.get("month_label"),
            "department": meta.get("department"),
            "strategic_pillar": q.get("strategic_pillar"),
            "question_id": q.get("question_id"),
            "question_text": q.get("question_text"),
            "response_value": q.get("response_value"),
            "score": q.get("score"),
            "overall_score": overall_score,
            "pillar_score": pillar_scores.get(q.get("strategic_pillar")),
        })

if not all_rows:
    st.error("No usable data found in the uploaded PDFs.")
    st.stop()


# 3. Combined table
df = pd.DataFrame(all_rows)
st.subheader("Combined data")
st.dataframe(df, use_container_width=True)


# 4. Simple aggregates (you can build on this later)
st.subheader("Average overall score by department")
avg_dep = df.groupby("department")["overall_score"].mean().reset_index()
st.dataframe(avg_dep, use_container_width=True)


st.subheader("Average pillar score by department")
avg_pillar = df.groupby(["department", "strategic_pillar"])["pillar_score"].mean().reset_index()
st.dataframe(avg_pillar, use_container_width=True)


# 5. Placeholder for AI interpretation
st.subheader("AI Overall Interpretation")

if st.button("Generate AI summary"):
    st.write("Here we will call the AI to summarise the combined results...")
    # Later: plug in your OpenAI call here
